version: "3.8"
services:
  backend:
    container_name: backend_pse
    build: 
      context: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - alembic_volume:/usr/src/app/migrations/versions
      - static_volume:/usr/src/app/static
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh

volumes:
  static_volume:
  alembic_volume: