version: "3.8"
services:
  backend:
    container_name: backend_pse
    build: 
      context: .
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - backend_static_volume:/usr/src/pse/static
    networks:
      - network
  
  database:
    container_name: database_pse
    image: postgres:16.4-alpine3.19
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data/
    networks:
      - network

volumes:
  database_volume:
  beckend_static_volume:


networks:
  network:
    driver: bridge