version: "3.8"
services:
  database:
    container_name: database_pse
    image: postgres:16.4-alpine3.19
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data/
      - ./library/postgres/init-database.sh:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - network

  backend:
    container_name: backend_pse
    build: 
      context: .
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - backend_static_volume:/usr/src/app/static
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh
    networks:
      - network
  
  

volumes:
  database_volume:
  backend_static_volume:


networks:
  network:
    driver: bridge