version: "3.8"
services:
  backend:
    container_name: backend_pse
    build: 
      context: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    # environment:
    #   - HOST_MACHINE=172.17.0.1
    restart: always
    volumes:
      - web_static_volume:/usr/src/app/static
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh

volumes:
  backend_static_volume: